- gen/gen_mpy.py
- gen/lv_mpy_example.c
In order to facilitate the merging with (regular) Python code generation, I need generated code which is always the same, regardless of Python version (in order to facilitate comparison of the generated code: refactoring of the code generator should not lead to a change in the generated code)
The current gen_mpy.py depends on Python dict iteration order, which is different between Python versions. I modified it to use collections.OrderedDict to get consistent output.
Only the order of methods, functions, attributes etc is changed, so it will not change the functioning of the generated code.
> Consistent order of generated code

- driver/SDL/SDL_monitor.c
- driver/SDL/modSDL.c
This enables Emscripten to work with the SDL drivers.
> Emscripten patches

- driver/esp32/ili9341.py
I’m working with the [M5Stack](https://m5stack.com) ESP32 device and the ili9341 configuration is a bit different than what was hardcoded into the `ili9341.py` module.
This PR adds a number of options to the initialization of this class that allows configuration of the screen size, rotation mode, backlight (M5Stack requires backlight pin to be pulled high), color mode (RGB vs BGR), and invert mode.
Most of the additions were made based on modifications for the M5Stack in this library: https://github.com/m5stack/M5Stack_TFT_ILI9341/blob/m5stack-default/components/tft/
This code isn’t specific to M5Stack and retains the current default values.
_edit: it looks like PR https://github.com/littlevgl/lv_binding_micropython/pull/54 does something similar, though I tried to implement it in a way …
> ili9341: add rotation, backlight high/low set, color mode, and invert

- lv_conf.h
Add the following optional defines to override default font settings:
- `LV_FONT_DEFAULT`: change the default from `&lv_font_roboto_16`
- `LV_FONT_ROBOTO_12=1`: include Roboto 12pt font (not included by default)
- `LV_FONT_ROBOTO_22=1`: include Roboto 22pt font (not included by default)
These changes were recommended by #54 .
> feat(font): optionally override font settings

- driver/esp32/ili9341.py
Prior to this commit, the `ili9341` class `__init__` method would raise
a `KeyError` exception if `invert==True`. The issue was that the
following conditional did not add the required `"data"` key/value pair
to the `init_cmds` list item:
if invert:
self.init_cmds.append({'cmd': 0x21})
In this commit, add the required `"data"` key/value pair to the
`init_cmds` list item when `invert==True`.
> fix(ili9341): fix invert kwarg

- driver/linux/modfb.c
The unit for `usleep` is microseconds, so the argument should be `1000` to sleep for 1 millisecond.
> Fix usleep call in modfb

- driver/esp32/modILI9341.c
- driver/esp32/modrtch.c
- driver/esp32/modxpt2046.c
- driver/generic/modlvindev.c
- gen/gen_mpy.py
This PR has fixes needed post MicroPython v1.12 due to the required MP_ERROR_TEXT macro.
This PR only fixes the esp32 port, same changes need to happen for other ports as well..
I realize you don't want to just merge this given that you're most likely still working with v1.12, I'm just providing it for the future.
> Add MP_ERROR_TEXT for MicroPython post-1.12 (esp32-only)

- driver/stm32/lvstm32.py
This means that GUI ticks may be skipped on a busy system, but that is better than hanging the GUI forever.
Fixes #82.
> fix(stm32) skip lv_task_handler if scheduler queue is full

- driver/stm32/STM32F7DISC/modrk043fn48h.c
- examples/advanced_demo.py
With these changes merged and applied to `lv_micropython` the STM32 port now runs without problems.
This PR:
* Removes GPU related callbacks as they are now redundant with LVGL's GPU support. Support for LVGL GPUs will be added back soon.
* Switches buffer sizes as full double buffering behavior has changed in v8.
(cc @prolomb)
> fix(stm32) changes for v8

- driver/zephyr/README.md
- driver/zephyr/lvgl.c
- driver/zephyr/lvgl_driver.h
- driver/zephyr/modlvzephyr.c
This PR introduces a driver for Zephyr OS so that Micropython+LVGL could be used as a Zephyr application.
More information is in the enclosed README.
The lvgl.c file is taken from the Zephyr codebase and adjusted for this use case.
The PR was tested on i.MX RT1050, with ELCDIF display driver and FT5336 input driver from Zephyr OS.
Edit:
Zephyr already supports LVGL (in C language) - driver abstraction layer is available in Zephyr codebase and LVGL as a Zephyr's module can be enabled with Kconfig.
For Zephyr + Micropython + LVGL use case are LVGL source files taken from the LV bindings project; thus LVGL has to be disabled in Zephyr's Kconfig configuration in order to prevent redefinitions. The reason is, that LVGL should in this use case use Micorpython's memory functions and not …
> Adding driver for Zephyr OS

- driver/esp32/modxpt2046.c
`lv_indev_drv_t *` was missing from `STATIC bool xpt2046_read(lv_indev_data_t *data)`
> fix(driver) fix the prototype of xpt2046_read

- driver/esp32/ili9XXX.py
I have added a driver for gc9a01 displays as a child of ili9XXX as it works in a very similar manner.
Two caveats, I have not been able to delve in to the c code and so hybrid mode is not currently supported. Also my display does not seem to match the datasheet for write direction and colour mode (both are reversed) and so I have written it this way in the driver but it may need to be updated if my display is an odd case
> Add in support for gc9a01 displays

- examples/custom_widget_example.py
- tests/run.sh
- tests/run_test.py
- Traverse all objects under active screen and send each of them the following events: lv.EVENT.SCROLL, lv.EVENT.CLICKED, lv.EVENT.VALUE_CHANGED, lv.EVENT.READY
- Limit events to 100 sibling child objects because events could triggger the creation of more child objects and cause infinite loop
- Decrease delay to 25ms and increase test timeout to 5 minutes
- During traversal print label text and widgets values when applicable (for debugging)
Waiting for https://github.com/lvgl/lvgl/pull/2354 to be merged, to fix a few small problems in the examples.
> Use tree_walk in CI tests

- .github/workflows/unix_port.yml
- tests/run.sh
To debug random crashes, catch SIGSEGV and print stack trace when running tests.  
Example of a random crash: https://github.com/lvgl/lvgl/runs/3013533718?check_suite_focus=true
Related: https://github.com/lvgl/lvgl/pull/2358#issuecomment-875968344
> CI: Catch SIGSEGV when running tests

- driver/js/lv_timer.py
- lib/display_driver_utils.py
`lv_utils` is not compatible with the JS port, as it does not have a Timer implementation.
It's also not needed as I use a custom event loop which is not configurable.
> Add fake lv_timer implementation for the JS port

- lib/imagetools.py
If PNG decoder is initialized (using `imagetools.py`), then `lv.canvas()` throws `AttributeError: 'NoneType' object has no attribute '__dereference__'` exception in this line:
`png_header = bytes(lv.img_dsc_t.__cast__(src).data.__dereference__(24))`
So, basically do the following:
1. init PNG decoder
2. show a PNG image
3. initialize a canvas: `lv.canvas(lv.scr_act())`
> imagetools.py: bugfix for lv.canvas()

- lib/fs_driver.py
If errno is missing in uerrno.errorcode, show the errno number.
> fs_driver.py: bugfix

- bindings.cmake
- mkrules.cmake
(proper solution: put conditionals around ESPIDF stuff)
Part of https://github.com/lvgl/lv_micropython/pull/42
> RPi Pico port compilation

- lib/lv_utils.py
Add missing try and except clauses to catch and pass exceptions from lv.task_handler() into exception_sink when using asynchronous loop.
> Catch exceptions from task_handler in asynchronous loop

- driver/linux/lv_timer.py
I'm using Arch Linux nowadays, which uses a very new glibc. It seems that recently `librt.so` and some other libraries were merged into `libc.so` and replaced by stubs ([source](https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html)). Unfortunately, it doesn't appear that a stub for `librt.so` exists, and if it does, it is not compatible with Micropython's FFI for some reason.
Using the value of `libc` when `librt.so` does not exist seems to be a valid workaround, which is what I'm proposing here.
> Fix error caused by librt not existing for newer glibc versions

- driver/generic/ili9xxx-test.py
- driver/generic/ili9xxx.py
Here's a working generic driver for the ILI9341 chip. I couldn't figure out how to get the rp2_dma stuff working in general, but if it works for the `St77xx` chips, I imagine it would also work for this one.
> Generic/ili9341 Driver

- README.md
- examples/example3.py
- examples/fb_test.py
- examples/generic-st77xx-with-xpt2046.py
- examples/madctl/madctl_helper.py
- examples/png_example.py
- examples/uasyncio_example1.py
- lib/tpcal.py
- lv_conf.h
Fix MicroPython binding to use latest LVGL multi-instance and parallel rendering architecture changes.
Based on [previous lv_conf.h configuration](https://github.com/lvgl/lv_binding_micropython/blob/8053b277cdad75973abb6fab93bb86d71c5897c9/lv_conf.h) and [feat/multi-instance branch](https://github.com/lvgl/lv_binding_micropython/tree/feat/multi-instance), and LVGL's [lv_conf_template.h](https://github.com/lvgl/lvgl/blob/master/lv_conf_template.h) config.
> Update LVGL and fix binding for multi-instance and parallel rendering architecture changes

- gen/gen_mpy.py
Forward declared struct has a None in type field. It's actually defined later and sorted to dict `structs_without_typedef`.
We pick those `typedef`s and set correct `type`.
> fix(script): take forwarded declaration into consideration

- README.md
- driver/esp32/espidf.c
- driver/esp32/ili9XXX.py
- driver/generic/st77xx.py
- examples/advanced_demo.py
- examples/example1.py
- examples/example3.py
- gen/gen_mpy.py
- lv_conf.h
- Rebased to `feat/multi-instance` branch commit [#56bf132d](https://github.com/PGNetHun/lv_binding_micropython/commit/56bf132d481c704601dc98530780fe36e6a519a6)
- Update LVGL to latest commit: [#a9960c62](https://github.com/lvgl/lvgl/commit/a9960c6216ac001c3c2384bed26c41c3c86c626e)
- Updated `lv_conf.h` config file to latest LVGL config changes (based on `lv_conf_template.h`)
- Use `lv.COLOR_DEPTH` instead of `lv.color_t.__SIZE__` to detect real pixel size
- Fix display drivers: avoid color format `NATIVE_REVERSED`, use instead RGB565 swap bytes function (`lv_draw_sw_rgb565_swap`)
- Fix typo in `gen_mpy.py` file. Related issue: https://github.com/lvgl/lv_binding_micropython/issues/251
- Renamings in `README.md` file: Micropython -> MicroPython
PS: 
this PR contains fixed (old) display …
> Update LVGL, fix display drivers and examples

- driver/esp32/ili9XXX.py
- driver/generic/st77xx.py
- examples/example1.py
- examples/example3.py
- Update LVGL to [#fe61f1fc](https://github.com/lvgl/lvgl/commit/fe61f1fc94526f0edb2e27fcfb7f0efef72900ac)
- Update `ili9XXX.py` driver to use `set_buffers()`
- Remove all `print()` from `ili9XXX.py` driver
- Update example files to user `set_buffers()`
Tested on M5Core2 device (ILI9342C display)
> Update LVGL and display drivers

- lv_conf.h
Micropython test needs to disable LV_USE_LOG.
> fix CI break by disabling LV_USE_LOG

- driver/generic/ili9xxx.py
- driver/generic/st77xx.py
Fix flush_cb function in `st77xx.py` generic driver. 
The issue was that variables `w` and `h` were used before setting them.
Remove also not used import in `ili9xxx.py` generic driver.
> fix(display): fix st77xx.py generic driver flush_cb issue

- lv_conf.h
Disable some components in LVGL config to decrease firmware size.
> config: disable some components in LVGL config

- gen/gen_mpy.py
For lvgl/lvgl#6068
This is a backwards-compatible change that allows gen_mpy.py to accept a JSON from the LVGL JSON generator.
Currently it only uses the JSON to find the `user_data` member of private structs.
> feat(gen): accept a JSON from the LVGL JSON generator

- driver/stm32/STM32F7DISC/modrk043fn48h.c
- mkrules.cmake
For lvgl/lvgl#6068
- Use LVGL JSON in CMake based builds, i.e. RP2040 and ESP32.
- Use updated name for `lv_indev_t` in STM32 source file.
> fix(gen): Use LVGL JSON in CMake based builds too - RP2040 and ESP32

- gen/gen_mpy.py
For https://github.com/lvgl/lvgl/pull/6688
> fix: check structs for alternative name in JSON

- driver/generic/st77xx.py
The `drivers/generic/st77xx.py` driver initialises PWM to handle the backlight with dimming.
On stm32 platform there is no `machine.PWM` module so this driver fails to load at all. This PR checks and skips the PWM if missing, meaning the backlight will fall back to basic on/off control.
> drivers/generic/st77xx: Support use on platforms without machine.PWM.

- gen/gen_mpy.py
- lv_conf.h
- micropython.cmake
Add a default callback that works for all ports if `LV_USE_LOG` is enabled
> (fix) enable LV_USE_LOG
