lvgl/lv_binding_micropython

- README.md
- micropython/include/lv_mp_mem_custom_include.h
- micropython/lv_mpy_example.c
Also re-generate lv_mpy_example.c with new lv_conf.h (some more objects enabled), update lvgl module.
#2
> Add lots of information to README.md. 

- lib/imagetools.py
As discussed in https://github.com/littlevgl/lv_examples/pull/40#discussion_r349786977
I moved array conversion to a viper-decorated function, but not sure if I am doing it right.
Anyways it works on unixport and gets some small speed improvements comparing to non-viper version.
> add tools for png decoding

- driver/SDL/SDL_monitor.c
- driver/SDL/SDL_monitor.h
- driver/SDL/lv_drv_conf.h
- driver/SDL/modSDL.c
This is the pull request for issue #64 .
> Parameterize SDL init

- driver/SDL/SDL_monitor.c
This fixes the bug introduced by #65.
The discussion is at #64.
> Fix a segmentation fault caused by monitor_flush()

- .gitmodules
- LICENSE
- README.md
- examples/example2.py
New batch of LittlevGL --> LVGL changes. Note that in the LICENSE file I changed
> Copyright (c) 2019 Littlev Graphics Library
to
> Copyright (c) 2019-2021 LVGL
> LittlevGL --> LVGL

- driver/generic/axp192.py
This adds a pure python driver for the AXP192 Power Management IC
> /driver/generic/axp192.py: add axp192 driver

- examples/Dynamic_loading_font_example.py
- lib/fs_driver.py
dynamic font loading upgraded to lvgl V8
> modified files needed for dynamic font loading in V8

- gen/gen_mpy.py
See: https://github.com/lvgl/lv_binding_micropython/issues/135
> WIP: auto casting

- tests/run.sh
Remove advanced_demo.py from excluded path, as it should work now after https://github.com/lvgl/lv_binding_micropython/issues/164 is resolved.
> run.sh: CI: Remove advanced_demo.py from excluded path

- .github/workflows/unix_port.yml
- tests/run.sh
Running one test for each physical CPU to improve test run performance.
> Run tests in parallel.

- gen/gen_mpy.py
- tests/run_test.py
When LVGL object is deleted, mark the Micropython object as invalid
Raise LvReferenceError when trying to access invalid object, instead of crashing
Related: https://github.com/lvgl/lv_binding_micropython/issues/177
> Invalidate MP wrappers

- driver/SDL/modSDL.c
- driver/esp32/modrtch.c
- driver/linux/modfb.c
- driver/stm32/STM32F7DISC/modrk043fn48h.c
- gen/gen_mpy.py
Related: https://github.com/lvgl/lv_micropython/pull/55
> Update micropython v1.19

- driver/esp32/ili9XXX.py
- driver/generic/st77xx.py
- driver/js/imagetools.py
- examples/custom_widget_example.py
- examples/example2.py
- examples/madctl/madctl_helper.py
- examples/uasyncio_example1.py
- lib/display_driver_utils.py
- lib/imagetools.py
- lv_conf.h
Related: https://github.com/lvgl/lvgl/pull/3501
> Align to LVGL v9 updates

- driver/esp32/ili9XXX.py
Added a specific class for gCore ili9488 driver and modified ili9488 to support 16-bit pixels
> Added ili9488g

- README.md
- driver/esp32/espidf.h
- driver/esp32/ili9XXX.py
- driver/esp32/modrtch.c
- driver/esp32/modxpt2046.c
- driver/esp32/sh2lib.h
- driver/generic/ili9xxx-test.py
- driver/generic/st77xx-test.py
- driver/generic/st77xx.py
- driver/generic/xpt2046.py
- driver/stm32/STM32F7DISC/ft5336.c
- driver/stm32/STM32F7DISC/ft5336.h
- driver/zephyr/lvgl.c
- examples/custom_widget_example.py
- gen/gen_mpy.py
- gen/lv_mpy_example.c
- lib/display_driver_utils.py
- lib/lv_utils.py
- lib/tpcal.py
Most of them were found with `codespell`.
> Fix a few typos

- gen/gen_mpy.py
> Change mp_obj_type to pointer

- driver/esp32/espidf.c
- driver/esp32/ili9XXX.py
- driver/generic/ili9xxx.py
- driver/generic/st77xx.py
- examples/advanced_demo.py
- examples/example3.py
- examples/png_example.py
Fixes for PR feedbacks: https://github.com/lvgl/lv_binding_micropython/pull/311
Tested ST7789 display on ESP32.
> Update ili9xxx, st77xx drivers and examples, remove lv.COLOR_DEPTH

- driver/esp32/ili9XXX.py
- driver/generic/st77xx.py
- examples/advanced_demo.py
- examples/example1.py
- examples/example3.py
- lv_conf.h
- Update LVGL submodule
- Update display drivers to use new draw buffer approach: https://github.com/lvgl/lvgl/pull/5204
- Update tests to use new draw buffer display driver approach
Changes tested on real devices with ST7789 and ILI9342C displays
> Update LVGL and display drivers

- driver/generic/st77xx.py
Fix wrong colors in `st77xx.py` generic driver.
Related issue: https://github.com/lvgl/lv_binding_micropython/issues/322
> fix(display): fix RGB565 wrong color issue in st77xx.py

- driver/generic/st77xx.py
- examples/custom_widget_example.py
- examples/example1.py
- examples/example3.py
fix(display): fix lv_disp_ function names
> fix(display): fix lv_disp_ function names

- README.md
Remove duplicated code example
> Update README.md - Remove duplicate menu

- driver/esp32/ili9XXX.py
Fix random crash of ESP32 ili9XXX display driver.
During testing an ESP32 device I have noticed that after reset the following line randomly stops the execution:
`self.disp_drv.set_flush_cb(esp.ili9xxx_flush if hybrid and hasattr(esp, 'ili9xxx_flush') else self.flush)`
The problem occurs only every time in that line. When the if-else statement is moved out from the function, and stored in a variable, then the problem disappears.
Other change: 
moved out `esp.MALLOC_CAP.DMA` flag from functions into a global variable `(_MALLOC_DMA`), and added `esp.MALLOC_CAP.INTERNAL` flag too (just to make sure DMA-able memory is always allocated in internal memory)
> fix(display): fix random crash of ESP32 ili9XXX driver

- driver/esp32/xpt2046.py
Fix `xpt2046.py` ESP32 specific touch driver:
- fix LVGL related namings
- fix indentation: replace tabs to spaces (these were used mixed)
- move "randomly placed" instance variables to `__init__()` function
- performance improvement: in `read()` function (which is called very often) use the cached reference of `lv.INDEV_STATE.PRESSED/RELEASED`
Source of issue report:
https://forum.lvgl.io/t/modulo-esp32-2432s08-ili9341-xpt2046-problem-touch/14685
> fix(drivers): fix xpt2046.py esp32 specific touch driver

- gen/gen_mpy.py
The forward declarations has broken things like event callbacks due to structures not being populated with their fields properly This fixes that issue y searching for the forward declarations and their typedefs and making a single object to represent the structure with all the proper fields.
> fixes empty structures being created

- lv_conf.h
- upgrade LVGL to [9.1.0](https://github.com/lvgl/lvgl/tree/905de3d7c81367608577e1e38d032831a7871c16)
- update `lv_conf.h`
> Upgrade LVGL to 9.1.0

- .github/workflows/unix_port.yml
- tests/run.sh
- Update LVGL to latest commit ([6adc0f56d6f9f0a795798eb4d2faf18c5fa1fced](https://github.com/lvgl/lvgl/commit/6adc0f56d6f9f0a795798eb4d2faf18c5fa1fced))
- Update github workflow `unix_port.yml` to use Ubuntu 24 and LVGL variant of unix port
> Update LVGL, and update github workflow

- .github/workflows/unix_port.yml
- tests/run.sh
For https://github.com/lvgl/lvgl/pull/8086
> remove `catchsegv`. removed in ubuntu 22.04
